name: Compile SCSS and Commit to Repository 2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Tailwind, PostCSS, and Autoprefixer
        run: |
          npm install -D tailwindcss postcss autoprefixer
          npx tailwindcss init

      - name: Install Tailwind
        run: npm install tailwindcss-animate class-variance-authority clsx tailwind-merge

      - name: Install Icons
        run: npm install lucide-react

      - name: Install More Icons
        run: npm install @radix-ui/react-icons

      - name: Install Sass
        run: npm install -g sass

      - name: Create PostCSS Config
        run: |
          echo "module.exports = { plugins: { tailwindcss: {}, autoprefixer: {}, } };" > postcss.config.js

      - name: Compile SCSS to CSS with Tailwind
        run: npx postcss cy_custom.scss -o cy_custom.css

      - name: Commit and Push CSS
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add cy_custom.css
          git commit -m "Compile SCSS to CSS" || echo "No changes to commit"
          git remote set-url origin "https://$GH_PAT@github.com/${{ github.repository }}.git"
          git push origin HEAD:main
