name: Compile SCSS and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '16'  # Ensure compatibility with Node.js 16 or specify '20' for the latest

      - name: Install Sass
        run: npm install -g sass

      - name: Compile SCSS to CSS
        run: sass cy_custom.scss cy_custom.css

      - name: List files to verify compilation
        run: ls -la  # Lists all files to check if cy_custom.css is created

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Deploy the root directory containing cy_custom.css
