name: Compile SCSS and Commit to Repository

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Sass
        run: npm install -g sass

      - name: Compile SCSS to CSS
        run: sass cy_custom.scss cy_custom.css

      - name: Commit and Push CSS
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Reference the PAT directly in the environment
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add cy_custom.css
          git commit -m "Compile SCSS to CSS" || echo "No changes to commit"
          git push https://$GH_PAT@github.com/${{ github.repository }}.git HEAD:main
