name: Compile SCSS and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 for Node 20 compatibility

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '20'  # Ensure compatibility with Node.js 20

      - name: Install Sass
        run: npm install -g sass

      - name: Compile SCSS to CSS
        run: sass cy_custom.scss cy_custom.css
      
      - name: Commit compiled CSS
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Reference the PAT secret
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add cy_custom.css
          git commit -m "Compile SCSS to CSS" || echo "No changes to commit"
          git push "https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git" HEAD:main
        

      - name: List files to verify compilation
        run: ls -la  # Lists all files to check if cy_custom.css is created

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to v4 for Node 20 compatibility
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Deploy the root directory containing cy_custom.css
