name: Compile SCSS

on:
  push:
    branches:
      - main  # Specify the branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Sass
        run: npm install -g sass

      - name: Compile SCSS to CSS
        run: sass cy_custom.scss cy_custom.css

      - name: List files in root directory
        run: ls -la  # Check if cy_custom.css is created

      - name: Commit compiled CSS
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Reference the PAT secret
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add cy_custom.css
          git commit -m "Compile SCSS to CSS" || echo "No changes to commit"
          git push "https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git" HEAD:main
